sudo: required
services:
  -docker

before_install:
  - docker build -t ricardoflnsousa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ricardoflnsousa/docker-react npm run test -- --coverage
